version: 2

updates:
  # NPM
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/node-app" # Location of package manifests
    schedule:
      interval: "daily"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

