version: '3.5'
services:
  ez-mqttrelay:
    image: ghcr.io/bblacey/ez-mqttrelay
    env_file:
      - ./config.env
    environment:
      - NODE_ENV=production
    network_mode: host
    container_name: ez-mqttrelay
    restart: unless-stopped
